name: CI/CD Pipeline

# Triggers for the workflow include any push event that does not affect branches prefixed with 'dependabot/'
# and any pull request to any branch in the repository.
on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '**/*.md'
      - '**/*.cff'

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.cff'

# Manage concurrency to prevent multiple instances of the workflow from running simultaneously on the same branch.
# If a new run starts, it cancels any currently running instance.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Set default permissions to read-only to enhance security.
permissions: read-all

jobs:
  # Always included to handle check-jobs.sh
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Run Shellcheck
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)

  cicd-pipeline:
    if: always()  # This ensures the job runs regardless of the results of previous jobs.
    name: CI/CD Pipeline
    needs:
      - shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Check Job Statuses
        run: .github/scripts/check-jobs.sh '${{ toJson(needs) }}'
